# Generated by Django 5.2.6 on 2025-10-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0003_alter_user_department_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
